version: '3.3'

services:
  sync_python:
    image: penguinw/research_work-sync_python:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
  async_python:
    image: penguinw/research_work-async_python:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
  sync_java_script:
    image: penguinw/research_work-sync_java_script:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
  async_java_script:
    image: penguinw/research_work-async_java_script:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
  terms_glossary:
    image: penguinw/research_work-terms_glossary:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
