version: '3.3'

volumes:
  static_files:

services:
  sync_python:
    image: penguinw/research_work-sync_python:latest
    restart: on-failure
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'

  async_python:
    image: penguinw/research_work-async_python:latest
    restart: on-failure
    ports:
      - "8001:8001"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'

  sync_java_script:
    image: penguinw/research_work-sync_java_script:latest
    restart: on-failure
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'

  async_java_script:
    image: penguinw/research_work-async_java_script:latest
    restart: on-failure
    ports:
      - "9001:9001"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'

  terms_glossary:
    image: penguinw/research_work-terms_glossary:latest
    restart: on-failure
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
