name: Workflow Run On Push

on:
  push:
    branches:
      - main

jobs:
  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.0"

      - name: Poetry Check Sync Python
        run: |
          cd python/sync_version/
          pip install poetry
          poetry install
          poetry run isort --check-only server
          poetry run black --check server
          poetry run flake8 server

      - name: Poetry Check And Run Linters Async Python
        run: |
          cd python/async_version/
          pip install poetry
          poetry install
          poetry run isort --check-only server
          poetry run black --check server
          poetry run flake8 server

  typescript-tests:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21.7.3"

      - name: Install dependencies & Run TypeScript Linters
        run: |
          cd terms_glossary
          yarn
          npx eslint .

  javascript-tests:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21.7.3"

      - name: Install JavaScript dependencies
        run: |
          npm install --prefix java-script/async_version
          npm install --prefix java-script/sync_version

      - name: Run JavaScript Linters
        run: |
          cd java-script/async_version
          npx eslint .
          cd ..
          cd sync_version/
          npx eslint .
  
  pushing_images:
    name: Pushing Images
    runs-on: ubuntu-latest

    steps:
      - name: Build and Push Docker Image - Python
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
          docker build -t research_work-sync_python:latest python/sync_version/
          docker build -t research_work-async_python:latest python/async_version/
          docker push research_work-sync_python:latest
          docker push research_work-async_python:latest

      - name: Build and Push Docker Image - JavaScript
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
          docker build -t research_work-sync_java_script:latest java-script/sync_version/
          docker build -t research_work-async_java_script:latest java-script/async_version/
          docker push research_work-sync_java_script:latest
          docker push research_work-async_java_script:latest

      - name: Build and Push Docker Image - Terms Glossary
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
          docker build -t research_work-terms_glossary:latest terms_glossary/
          docker push research_work-terms_glossary:latest
